baseURL = "https://sbkandhasamy.com/"
languageCode = "en-us"
title = "SB Website"

# Main menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Profession"
    url = "/profession/"
    weight = 20
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 30